import argparse

from os.path import exists, dirname
from json import load, dump, dumps
from scripts import util
from tkinter import filedialog


here = dirname(__file__).replace('\\', '/')

if not exists('scripts/settings.json'):
    obj = {
        'download_path': 'data/',
        'is_bh3_existent': False
    }
    with open('scripts/settings.json', 'w', encoding='utf-8') as fp:
        dump(obj, fp, ensure_ascii=False, indent=4)

with open('scripts/settings.json', 'r', encoding='utf-8') as fp:
    settings: dict = load(fp)

def download():
    if not settings['is_bh3_existent']:
        print('Honkai Impact 3rd dialogs not found'
              '\nThey should be required from the author of https://bh3helper.xrysnow.xyz/'
              '\nSee "about" page of the website for details')

def _get_ext_name(filetype: str):
    if filetype.startswith('*'):
        return filetype[1:]
    else:
        return filetype

def _ask_file(filetypes: list[tuple[str, str]], is_binary_output: bool = False):
    def wrapper(func):
        def inner():
            file_parsed_name = filedialog.askopenfilename()
            if file_parsed_name == '':
                print('Path must be specified.')
                return
            else:
                print(f'file path: {util.cyan_char(file_parsed_name)}')
                
            result = func(file_parsed_name)

            file_saved_name = filedialog.asksaveasfilename(filetypes=filetypes)
            if file_saved_name == '':
                print('The path of the file to be saved must be specified.')
                return
            else:
                ext_name = _get_ext_name(filetypes[0][1])
                file_saved_name = file_saved_name if file_saved_name.endswith(ext_name) else file_saved_name + ext_name
                print(f'saved to: {util.cyan_char(file_saved_name)}')
                
                if is_binary_output:
                    with open(file_saved_name, 'wb') as fp:
                        fp.write(result)
                else:
                    with open(file_saved_name, 'w', encoding='utf-8') as fp:
                        fp.write(result)
        return inner
    return wrapper

@_ask_file(filetypes=[('JSON', '*.json')])
def parse_file(file_name: str| None = None):
    '''The `file_name` will be filled automatically.
    '''
    from scripts.handle_bwiki_code import parse

    with open(file_name, encoding='utf-8') as fp:
        code = fp.read()
    
    parser = parse.Parse(code)
    return dumps(parser.parse(), ensure_ascii=False)

@_ask_file(filetypes=[('SVG', '*.svg')], is_binary_output=True)
def build_graph_file(file_name: str| None = None):
    '''The `file_name` will be filled automatically.
    '''
    print('Loading libraryies...')
    import re

    from pydot import graph_from_dot_data
    from networkx import nx_pydot
    from scripts.handle_bwiki_code import build_graph
    print('Done loading...')

    with open(file_name, encoding='utf-8') as fp:
        code = load(fp)
    
    def convert_to_graphviz_label(input_str):
        # Generated by Deepseek
        pattern = r'^("?)(?P<md5>[0-9a-fA-F]{10})\1\s*\[speaker=(?P<speaker>[^,]+),\s*content="(?P<content>[^"]+)"[^\]]*\](;?)$'
        match = re.match(pattern, input_str)
        
        if not match:
            return input_str
        
        md5_quoted = match.group(1)
        md5_value = match.group('md5')
        speaker = match.group('speaker')
        content = match.group('content')
    
        md5_str = f'"{md5_value}"' if md5_quoted else md5_value
    
        speaker_escaped = speaker.replace('"', '\\"').replace('|', '\\|')
        content_escaped = content.replace('"', '\\"').replace('|', '\\|')
    
        return f'{md5_str} [label="{speaker_escaped}: {content_escaped}"]'

    builder = build_graph.GraphBuilder(code)
    G = builder.build()

    dot = nx_pydot.to_pydot(G)
    dot_script = [convert_to_graphviz_label(l) for l in dot.to_string().split('\n')]
    dot_script = '\n'.join(dot_script)
    
    Q_list = graph_from_dot_data(dot_script)
    if Q_list is not None:
        assert len(Q_list) == 1
        return Q_list[0].create_svg(encoding='utf-8')
    else:
        print('')

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('--download', 
                        help='download the resources for the exiprements',
                        action='store_true')
    parser.add_argument('--parse-file', 
                        help='parser a given bilibili wiki source code',
                        action='store_true')
    parser.add_argument('--build-graph-file', 
                        help='build a graph from parsed codes',
                        action='store_true')

    args = parser.parse_args()

    if args.download:
        download()
    elif args.parse_file:
        parse_file()
    elif args.build_graph_file:
        build_graph_file()

    with open('scripts/settings.json', 'w', encoding='utf=8') as fp:
        dump(settings, fp, ensure_ascii=False, indent=4)


if __name__ == '__main__':
    main()
